# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e91f9acea2bb0926a85facfa17b03121be5a1e9a461f04bf65e8633410ff32335e50b72ac57242252aecdde9aee20e2020dad2fc183e64945f4fa21a921b462

test:
  secret_key_base: d32d086a2da9c515a03af271d9b40f68a8a8be33dbb73fc7ab1b4ed4dc682ca90fe7f91789dce2084a98dd2e56ec2ab0d318ef065fe1c9133399afece2a77df7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
